import os
import pickle
import google_auth_oauthlib.flow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from datetime import datetime

def upload_video(file_path, client_secrets_file, credentials_file):
    scopes = ['https://www.googleapis.com/auth/youtube.upload']
    credentials = None
    if os.path.exists(credentials_file):
        with open(credentials_file, 'rb') as token:
            credentials = pickle.load(token)
    if not credentials or not credentials.valid:
        flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(client_secrets_file, scopes)
        flow.redirect_uri = "http://localhost:8080/"
        credentials = flow.run_local_server(port=8080)
        with open(credentials_file, 'wb') as token:
            pickle.dump(credentials, token)
    
    youtube = build('youtube', 'v3', credentials=credentials)
    today = datetime.today()
    request = youtube.videos().insert(
        part="snippet,status",
        body={
            "snippet": {
                "title": f'Bev Facey Announcements {today.strftime("%Y-%m-%d")} (AI Generated)',
                "description": f'Bev Facey Announcements for {today.strftime("%B %d, %Y")}, generated by AI',
                "tags": ['BevFacey', 'Bev Facey'],
                "categoryId": '27' 
            },
            "status": {"privacyStatus": "public"}
        },
        media_body=MediaFileUpload(file_path, chunksize=-1, resumable=True)
    )
    response = request.execute()
    print(f"Video uploaded: {response['id']}")